---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: filebot-license
  namespace: arr
spec:
  encryptedData:
    license.psm: AgBKt8V2x9gpbP2xFxWEBYsQpIVtHevYEzzF8ZpqqRhGhmplckryRp8v4OXhu6vTivIqZ/CA7DPImpkUJi0Y03wK6552IQhD/SDBL6vYk15og4lNo4hkgUrWYpQlN9X+JQihYWo/Hsml9xjZnZqc84FYZm7vlze47KUX1Ut2cUbtFntCqISFHaXmONaWbtR931/hq++szNtnQFQP+jYfmNT1QCXX6lQFeut685Xx0xp+XU60RYNE/qYXL2OIJTQy/aCQx7oYiI3V583PvBTPkzGvuF37DnauEv/uXmDdxziOIqGP7gWklknWlUWIRlYXN8rVkaZnSb5HRwFgoEoyRQtuPN8Jr0w4YHj+Ml625dopdFX5NeNiqEgDEYMuRKZNS2wQPtiqFeTs72UFXwDG2sb0ps8AVd8n2zy5CwD+HXd56HHHUEAT36ixsatmfDAFnXCpDvzYHUwzUSxCAS79mVethKM7QjGjUXs8jrUl3pr8Fe+CFN5qYRItBDrevVbcEOQIi2SOD7ziognOAJOF+m2rTlMbirDGLjM0cRaHaYdY3YQ8zXMqfDZwo3Jnhpdm6FzaE0GRv1+FZjt1TUvccSrXuLIx1y8/rx2iClzL4CIgubOvJ+/1qVjlA3+iGwk/Le7N6FH3bW3sSH9GkN9cSLQW5crAFcGxcAxDucKFve+3UTHmzmMxO+Kswa81YUeeu1Ii4S5UHTzXE+6wwv0YSNMgj0W4A621ALFiQobYwTRHP7vVvYNREHWKSrhd8oiOj3XTh9FzIJTN0rrLf9uhir7794WH3jzy/k/gXSoQ5Fa0RxKLxdSjV4GGN+qp1It/rwG27ZDe3XnM1iakRbQkFm3CLRcIGktRxbH3hL5SQKBKNtYyN+6uwQBbfo5LP/f/4LnDIZP4uM06owKPjFNumJYBlWaR5rLr9Z+OXHwg6riZ7FoQ6kR3gadpCfytm812byKiAkiQdczJhQO/VLlxLWJ44MDV4jInFSQogCpGGJaL/2RGb/qyUU5vjeLSRrP8LMikVL7Pd5PT8OVd6s6LKnXhc7fqkmln/VX1fv/Un+iUQX3xh15qxuNr/gH/cAYNyzOlr+BlekMSyfs/s5tGxAoS5aJi5X22RogIkUygLpQC0BwI8rCekqMcJW08TzachVchVHI8MwvzVGfrqsmMSqS3d9VfjGTFimxXNtm8X0GL7yZ4f0mO9mP4Z21SOKaZzX4EUy4U81BrUo75FsswE40DX5zYx8+Q+C7ma4zMBFME2TsI2kbsjik8esFXW0bg1DBqqJBIWl2kTNMON74MIvj6MNlc+O6WQ57dbGnfGVTHBcj7Ad2yV2VxAmSZyUK4QePJ13mgfb4WDcQJPkobo58nv1xCdAEJUXyup3jUfEkJ0UkAfSmXnqKbJTeGojRps8JAm57W+NKUNpnvNyIBi8KnrRTeIedFBpSO7v0yAyb+JurnrQlXQw2visDLL0rhdIYgGFpiFcYiLwLTf7P8qrwHwsf7cEmmqZ3g9cWJmRTS96RBBiL5zsJpu8X/baTi/wQm49RzbkHYLkv7PaBE2ZI7VkPnyMEZKR8MnkpryGRNRenoYQ==
  template:
    metadata:
      creationTimestamp: null
      name: filebot-license
      namespace: arr
