---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-media
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/volume1/jellyfin#arr-ns
    volumeAttributes:
      server: 192.168.1.3
      share: /volume1/jellyfin
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-media
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: arr-media
  resources:
    requests:
      storage: 5Ti
