---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wallabag-secrets
  namespace: wallabag
spec:
  encryptedData:
    app-secret: AgCLpbeaJRnUrKWcYr2pc5Cmy9p5php9Kk4xJ2P4ZgkoqNKFG6LbVo5cHrg8//ZkcHC5Iu9qdpzp+UuPZzKoVgtP/ABDgqXEV2jYZsoatlFd6Iap1NItAch7/G09SbiRDRucRqB6Hj6+neIholMYNSwbjqh9f3YpUW6wrGtYmaWaRCLHVFH2W8ZDGs91+Dor25QEkHv/CbTuUw+esyqZOwwJLtLZXezjlw8QSYqtSWvA76TGt9ubuTg8/t8gBylmUER7hpRvrO/JQO9U4FPMaZI/ULSLw8tSPAL1voxzuxajafNEl6C4rHkRhvXKZYSXLjiYKDUQnWW6iY0PfdfK+PbKdxvpDaCtXhsVCcmab8Y1VlWUqNFOpLyaubIKSqNiZKy5xVIPHnSyVPE/t/XhwvAG0e+c68e0in56bY6tr3LqIeR89U4QQ7sv52ht6gH5w9BDmPGYYvIC4dfA1o6bFwRJYj7BgTHaknQ99z+GCrD2trJ6dyTLopdpCxqd71irApaazu/6ZJ8srg6pvvuLXnsaQ+ZWsnMzj3qjb2o8cAiL5F8EnyQcSx5cZCLslFE8UFNk4XwXOKofUet3t4sLuUMXgppfA9nQ5Aqa3Nk9J1TEFQyJraD+EGoKU9FLFhmWXIGX03t7l4DswVqtlDhYAkLY13XkuCRro1UfI3NHJdgL2pjtLepNtG6TFLyPVS8ETcSuvUn+/ORLWSO5E9pxfgAOOYjNSN60cmdrTNbE5tg+HV2ntR6VtGQamzNAF07cR63NaHkL4yMd7zSAEluhrmdw
    db-password: AgCt0BdMRUFJaXRQLa5ib0BzSsDeORXDkhH8Y75U0MCx98huqPZCbtGZ/SN1sQDcmBOu4xDJIsXYKc7Qlx8Wyyqb5NLybl966G0DVQs8pFuRXMChdytJqsDgFcuot7SHtUkA/VZr8i8ct+Sy+W0evHclKZi/kpqTvCylnposr0ytOEzmWCKTvZf4wh7lsfTJua+QrtMJUQqtxG7+1JzsvwVOCj0L764nyLWG9uZ1AkM2E4ShZ3xwrFIQ2UDuqO9zXKF7NAw1K1J1CGyOz4BVyV5jdHDwC3UuWEn9vjDBNrfNgObACUZNal4Iwb06JwYOdTkcQCqTFRjtBK8380hMHe5KEmfStSwh41wKK2oBdttJj42uVudEqOpp52HrEXykMXjRQjZ9wxIMVtVA/Ie9vpIpK5C2aQILXCJ+QqBXmNQw7Ys2ZlRXFxlt5Gew3IW7YqVTRe+Q2PYKnrbJTXTVkdd76UzoK1x3iTMGK0pki2vSjvxUeiCmxLx6z9k9lknQYbrnlvpvJPnHv1o7uTR5pP83sG/q91/Z4iAf5dRTo6V9nVb8ilpJ1ZNzMj6S7OdYoSLPFvrWrFXPZ6/pSp6yecQmmhWq176DDXSrFlBmbm8F0S5rOJW7weAGUz/YF1zrI1RDTapNP1oOfb6/3zRtR8E2mcrndwOwuvpXh7eB21wi0A+ppRxHh0MnaNb8/AuqAjIfI3mf3CZnW2XvediO36jJs4cUrqc++vh6+YNV9EcTGInloIVZRtogvaW8wA==
  template:
    metadata:
      creationTimestamp: null
      name: wallabag-secrets
      namespace: wallabag
