---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lldap-secrets
  namespace: lldap
spec:
  encryptedData:
    jwt-secret: AgC89ypiP1OfxlzS3B3lcVxfttOMifaGii9BzzRFLof38SB4y0or9+I7oxpDabHkWBn42yypRBwRytdEOpHuOAyTvJQrYf7oRdA3D7eOcg23pHjs+Kq2oUu/uqMVc78E3UL5oU62ZiCF6wnfcf2VfwBjxe4qQ1+VJOyOEFWCWXMcMU3N+cGkPohP4/dudsgD1+X4DY06r6Tvdii6p+pmAkHyAk9pXRBAQvR8QQ5XSa/jIla03pcRijXJoCncRe2E09Tnq+Jq8VVMC7HLTf3/1o8w9k7Xhf6z5AEb7WcVHydbHCbUvK+Y+n3L7Ij739B663b5iOtTiP6rHrBNDMkKh07tY5nWbBGVuOMYXVJG0IDWSXDiNqYDjake1mfGHkLpozuw/ctaQY6Hc1vqFmlPIT3kO7LXfXPV14SpPIzrxgdhwA0oJmEpLlwiA2ktul9XDHz/BPNTeeoYmQvSuEHe8UhwmRSRSHp/E2hTk3nCVrqogE/tpYCddCcmwiMDKmpHROkyYQXULd+5zoTdqq24Kx1Co0bLUVkUKrTUj3eLxoHfUTeUO0hIKehj6wsWcWIGuynFquJuZkDdZsFv37OPIHABPWxbVB3KGUsYZDgy2UDlpadUdHR9RChdS30OM9AGEivo93bnA3g4lKJKUfC2VhUrRD7k11G9Fr7k5G4AOnbvg22jdJ/dwQMqY46Wxy5wm3k8V+LWgrPI/fpPgPxhzrBjViLAUgvbTcY55YZXJi/M6wjOUKN8zDWJm9R7MQ==
    ldap-admin-password: AgBSX27JxXrKt4BH6ZV6txZe6BcPi0+uhAHN4aN7G70v8Fw0PpM+rY1XriBgyVFSLF0p6JENHZBHzCCK/KtnZ9eO2x0YElnMIAdfgHB25AC7msl83/Ez7yRe59k1GW4rxtxem5b0ueYPw4sF/uETjuT0KKAByZgmiDAZ1mLWz5f9AHSwJ1VkByHNQog4zgkUCdyvRBAbLU19FOIbDiW2jUr5tGLn+iV8iX7s3hPaRmkvu9TVgUTLIzYACEyqKzRzFLQyo0MBlpIn5BQVGNSAT+st/76KPel3wceeZDXqF5NmEY23cw+v+p0n1BURitjH6/DyKbtO1eBHM3r5TVyWAmfucq48deLNuFWZSdIhpEACLNqX0qz3fVvGh3j4qtxbzTBiqFkfl9pqrt/eQvxdbIgT/KAV/bfJps8gx5x0FNcTGHnhJXy3eQdHfO2Co6ild73kPju5pSkHC+QZdVIEgwVxUVpXA+kTP5kCH5piPAmpXwFXm9ZmwqoSsYXjASg9fpOqddhG8j2SsUxBNZhKdLxwa+aYA1uVBNwkda5qZGuUlicikTCS5L//Jr0IiZ70s8Ioz7X3TodtrfE/1WASwQmhaTTnnJywEwXvv3215ifTOKmkEFepbKevHopm48iPLnKe/ciWyMzv62NGgSUYxUA7ZfaHwkvF7CjndJfowbF/kY9T2de/wNWpJJFbOEVBAPbOH1W0fun+oA==
  template:
    metadata:
      creationTimestamp: null
      name: lldap-secrets
      namespace: lldap
