---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-oidc
  namespace: paperless
spec:
  encryptedData:
    providers: AgBYnsw0TY+tVZiJqBDOisno3Vhq4h3EYJ94ZvCiXr3JjwGDHSrlUjuks5MYXZGzdj+6vkBBtyV+VNZ72KAgGjaEn5XAk57FL26DGKaRXO4WaNWzmpWumuoaoJmGIl/63L1zg/smyszId3JMqO5MpjqqoAwkNL9aHk6Evpofbyi+CTa/+jwMeQB/7yE3TA8Vy7cengyE1ft0ZeGGGa/ykmTk/7Idf+HzgAIq+myc0HM1Z81mJ5FU6wiqO8ymTYxkFyuyXwAh2XcY2o51OvreZH7jL0xf6Leo4d1ogpiiW23q46CtVlStqcJFkBVUYgEaiMKfHsC73dNCLR3S3488xbEHzcR2I3nCN4fI6i5SH2y6hRDv8CAvloO9Xl3mx+8YQfDbvbtI6AuCxojoM+0BSRWeyIwyKwAA/Xr2gv826I0y81c3oF17y95PJA22B4YdU6WsUtyIk5fNYddQSKScZzVjVnGYmxFbDqtTKoMyLyMHP7HXFQM9ljfTY2FuX8d2yqrRWc8tVGSjLRdPB7zNxOSjn6cGxSIlCBAC0pKjCG9/wItpX0wGwdFJzUoiRnbMEINmxKmou73YMncQab8lHq5TJekHOXCrml453t4Q6F6eAIA3n19hdRrRqNl9/HnxRGL4IH6t+OVxCl+HBPVQG7BQR1+SWo/xGXxV/af1K9xdBEsQWWLtO6xOHV9L+0j/uYppiCdoQ8lMTSa1ZJrVnkhXbf/R3SmheKGbfc6XIR5xTLCTpwdEagP93VjTdP24n+zJoEph1OIH0iPfBBVHLpdJLFskeVwJ7eBgPRDkKtLIND8n0WIKgFuJH0YJxIPswG5AgWhKkUPNqOV0notL/WTog2zn7ihjVDxNyqOrebRvA5Tc0uEATCN5zXf8ViIUMxCIJpaD4b7l6REiT6DPhEWGSo7LoS1k/MXBK8OYY5P0VsM5RnKvaQhFpW7EKbNeRI1fevMjpO11yacw1MLQrt+m8RIuz+yFgISnk0NqGcGtiesvZQ1RDFG6BoaZIgXR7oOKuK4t20ycLUhU3HN2SWXRd73N85EfTLf64CjzMxOgqiEMhvSrV8jcAEE95weACIpxVhxSvcmFiqJBs/0kPYYRR6Zeyr4TpoDredCWZK9+nYEn3diOzmrYhCVwfyIeOa6GzSt2RW0FOfPvhdMJSSiPts7l3JDCXPgxyDzG4366a5q5TkkYkY36H71OPowvGa2xYYcx+c8=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-oidc
      namespace: paperless
