apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Run argocd-server without TLS — ingress-nginx handles TLS termination instead
  server.insecure: "true"
