---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: collabora-secrets
  namespace: collabora
spec:
  encryptedData:
    password: AgBth+vOPZwVCOOmswzYj40+waCcPEvBrn73cd3iy4W0dN8SEvEuS/JbLj+2IHsdialFaOzrbJ9KnPIUxyuu/7rN6SmDDgJmUS7VOiIEb8sOI203X8SiFyBIXvO2hq5SqDPfpJaCNufE36YCtolOr5DF0HsptgR4NbosKccgLZWO538e79ZqgzfzL7ykT3R4HqQRT/EY/9AItA4Olr6sbMBj7nWZ/HhwsjCJIkiDFVvBUHtg6WF3L12neH/FuS6oSXhm3p1ElpjhLIm8+5k1fdxnwNoY+ijgySsdtrNt8m/6nkr7ZwDWCg6T4GqDnumd1+JQ1AJjWfDPjvN6QawndpTgyQa7NR9PCZf6E9kbXGBRg18JaK61rlsse6i2lHaT0MmJtaJi4K47UuJJLrn0w4wjCMv1Wfd+WpqQSi7rq1owcwsYJ1BUGBwpKlZSsoKJdS/fPvBjrpYjJHRz103sCxvRg6shRjMcWyeerDxmMlNTTJXoC9cPgscemo2cr0nMKADJ5DjbJdMJkdPRQHn5CotTk1UT73yHuCjTC91/UXCTDo9g078NXp5DJvTjpWQ+H5NbbskLdN9/stdE+5B92U4DX9+Vgd6H1ach80hdh4TZlOmS1fOg5/osEouvYIoa8kSnfN1PqgqEDlJ94/580s1XxvWRLRPz0/sy3nUneRtlMudKq744EmH5hNLFr7Z2avi2SgpiZSdGkUGF95rZRxvhk05mzoWSNrH9uXZKvYhABQ==
    username: AgDNBG138hQ/Ey1/grqvI8qJj7PDlKW66pSQGgVByh78hEyYDYo7FgGzJU9vwZAAyGsbdq8J79QyZECyQY9oYvEH7GSy4aQmeQrCO8FnNAmkxpZasQwDVwrmEfqxGS/XeVhn9vF0haJextoKLmFg9j7scPbrUW5eK2NzEprEUjoLXhY6bAY2ijNg5hKVYRQG2YQmJ0MnDIeFI1MaZ4XGcbNoWJSAZpbXx5olzfxGRr/d3RGpWOm/o5WHHLVvBSyh5UT+0UUx2fpVhJM05WrW43ZJzHJwYqUU8cPtX4RGzyuSMmcIgDZ6KEgxR5FLb8C9VoPaS7CjGeHPqtBtlzj/Hk3lRun6BbxvHhZJR1xVh0WBdppc8RPSk9Rk/t7NzXrc8QtX3bf9m1gB/xMO71PqM+wZjiiHhXiZ2mmZoAkm+ejYa7uhZRhUhjPYwfKOHXnz9fJaD56+wXBcCECaMWZlDzOSgBtwWNoCdkPrW8aE730tYX4A8ZljwdSlwJX2/96z/8yKJnU5jzSGtsVQZZ9RDSSPFedxFl8aZHeI5H+VgJafenRL0o2t94FJod6RJwkOzXI5hyqZ17pOS/t08GifXCp8XaY39Wf4YLcS1SoeuzfdOhTdOzijvbifylsAUCcsiW9vyWgKPsx15YkA699bUGewyYGbChFDH9Mu7wrKrgrl1Srv2eBwNOBSz7a6C7pgfZWHjQQXJw==
  template:
    metadata:
      creationTimestamp: null
      name: collabora-secrets
      namespace: collabora
