---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgB3Cj2sH1RkKK6vmGaBMlXQEZAxE/VoeJ3fY1wAcJZm0KyPj/H/345qIIJ9ZiD7CGGVfMaKmGzkjvZ8PGXFrp8jQ66gPBxpxwTHGewiK6mbIb53TfvRUktAY3H3aAcz36G8sfJCxDdjKM1oM+MXGSJCrejzraXhbm2gkQxFgevOBn6DXxYGhfwQh82v7Kb5nU74pCu9tb6JFr31AMbCaTtkPjI/cFpJiASb6Iu8hcK45Vk/0e1o1LDJU3eTWUpBcuAj+PwMaZlbnZZNjT8KaWexl8fZjCvww5bf8DRSpPvYXic+5JPfhtu3wiN08uJRM0omeCxM2q0TkCJC2JVXZqJn0wcE3q1JfXIlH3efcDvOdmLFDDMnaEJbPV4QWggNBzUrsXucRfdSrc2ZQMoUBhWEI1U9v/M6jMCvpg4ugQ3Uoh4V03GzGR1rSr062MzDNBGf5MroqzER5dKw1aBSuYiEzHXdqGM5C/p8/NrTZbJ1UFuE84WBx8zO0QO/mJeof9MvbO6cR72WFXwtCwlbIM4T7J88dyyIoierrFIgzyj78S9c+U6KX1SYE0Oa4FuhIndFTWsC6KAgaJCJleSsxfjQMvTIQphiuyZNWh2uNLFJvUkKDW9vlB2zUz96EiFgZ/DL7yer/WxrCJmE8nwqQoPZraknOAisUycLGBJE3+bCJUK6Z+5RKQhF33PFcro/dfvF7Z4dG9y2DYbO9K3w4iNiAQ==
    client_secret: AgAdCBp2Dw1l6B+o59WGU1UsULpPlT1nBHxZ3nwI1LR6Pvg6PvyMCTBOY7ewxmkIaWLsSxY98vWhYQ0aNrkiPgI2PBieS6WO/0usAIhhcCwOT8fApk96KcRZ03pEGagE4/VjZU4AJzCUpla1TINAQ3byB36WFe4KfRueU24m9Qgrdf1PoQb4C8sDi7WphIYDvJWZgbN0Eutx7sc9c3Juo9CUqJbaW7s8MeSBKLD5wALvPAPq8nFOPlHv/YY7R/J0USxokrOBjWGElnBE5lmxoOkrKROG1ijb1nPmLikTtMfIxIzb5rK0Yg5CQlrG+Il+R58FYYNRjcDnjAz9u+5jZzS/MNO2ob6z+lVOGeRqOSehpmzaRhZ5XKlg/CqlLuRmilIhAZypsBmuknlw01zQz3/0LUtetutoTFiFDkqp0fRWWqkKBkWaIJWQt8PLbFfHpOPGC8e+a+oKMIx9DBCGeW2b2hdJywQy6VXTKctpNu4bpCqgQuVcmjOmo1u9pRh1NSn/m5mJ4rVcs4VNUSkPOPbaFn9NQfzezpmXsum6yI9oviI5kGnmMjo+qt9cX7qiVwfivPo9qJaVRfv4ba+8Y+5VtlES2DUOeVp3PDie8Vf4Z4BT8pHvWwIrRwGlwD2shUEnvQ2V2TPCDRU7VGpfQOnhXsXIabz5D+Bpn30OwrrilvOrVQoC0k8SJP4FtdSGGnf0UY996e6VJLfTR867KoXsOIjlRToyCxo3fmuSEqSVxwUiJzpG/CHRJT/IBIscVfTBItvHaLWD/b/fwIS+4H0f
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
