---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCyE9Of1IKrkeKwyc3LYpqSj23EOK5hJSCWa/VyhgIUoQm6vW1g0zZFMA5V7j9sHrtJ7ckPbTgrDpnXsLSCESy9u2H9xyGMNAXtI2Iuk/LDVjsAvI4JZakANC9JVEDMRxfObeU6YVhmQpp8glY+nYD2/s4kpOQnbr9Br/x0odAKaNmnqkGCIMOowKCH5BQktct/f7o94vA+P1B1Ne61Tg7mzuCEVoSWY6sUxU6AUVW/YyspAfMAhJGGLvgcLVBN0Ztj51BXdi2+5ht59BbMBPAAJR/Ww98uzPPrBOYVlfno/q0t221hkZFu2kLVbz0eSIqy/glqK4Rnyu8u/psaspDnfBkH95rpXmzctiL1J4tQJy6SVyEGINvHb5LIUh1nXrEWKwOv6AhG2k5tmnyvAcrhtKmy6DHRU7gyeWIBHhwOlMv1x/wBSUIrt723CXN/+lpB52v9n7V+HWfaoKrmf/unJZQcKkc6VARFS43sGB2Zb5puIhbdyYyVgVx/l5iKmkIjg5VcOk0HJ68nxw0Li6lX1t2GpSPj5ubLDxRnDSNnTIOFbdKafdjv2Z9baAnpUKDmoaGqPeSDheoic31rwnMWpYVKk/CODiWbGB5ejCG0mx3iNlwFcxGmbslZyjfUJ/ZeUEPQq5KaMaS8oky38i4NTipckgo2J3FJFyrwtFUDoAUW9oaz/yPk766Y5OQ21rzx+l7inIkYa0B7roK7CoUuFuyM/A==
    admin-user: AgCID7ZQWjhLhokQoWW6IV9hPLLeZgnZz8qI+aZyNISX9ons6twGaNak1/BhrOdl5y+U8pwftyQO9AjQl8w8WuLJc/j5GXVTgS3P44PUNdnfzzLljge7El0q/r4WJZImZNGC4bMFxJOLkLq2SnX1k7AjjaBa6yNSJPgpkBMaMdDTlpggYxcomtBglNLpGL21eVzz6pjllHEzLnp3GnstulMfnQFZKaB85orOWkgfQ5JqyDA0H9rqYLHwJS9sQmdY78qEBKKV3T6pvv8xPLEhwZK+1iZq1B4EDls4sUfp0tUuxzhksBpzzRsKqdZWIMSqko3P4eef/c2kuiM2KidDhcyv+d1Ga7H9TuX6aQsL6SMYxE/GWsR1bdECmGwAhtUBrK43bHzLSwDNa04/4TV/329vpV5vqN7s1zRHxutQahQ9o8WZn16C7CwScNdP9auh4fV8ps+UahNawVn1X3Fxl/y8/aRCkmJDDFl48GUu3LtSzMGt2G/0yb3GwHEWPzEkHni8xjPVf88B2vk8CD0wkhJUppj+4sjUybxya6b/pZyPjH1R8upFECXux24AKSaxpIfbyGrHqBqzd7h6h2jnVhrQsGQzaoch2E55pG8ug5raIoL849STHRsTqeXoSr/bghO4B5B1lnbXcT5gEFXOw5zYFKKCIgVFEyaBPICWwr6+BVNfn41oNzHIHjxs+IDE6DzCHAZ54A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
