apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Wave 5 — after cert-manager is ready to issue certs
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.12.1"
    helm:
      values: |
        controller:
          # MetalLB will assign an IP from your 192.168.1.200-254 pool
          service:
            type: LoadBalancer

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
