apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:vbdjames/homelab.git
    targetRevision: HEAD
    path: infrastructure/lldap

  destination:
    server: https://kubernetes.default.svc
    namespace: lldap

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
