---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-db-secrets
  namespace: immich
spec:
  encryptedData:
    db-password: AgDCAj329OJcDEBYpnfJC/umyVJ+YNPCIBt7JAAPsO2WqgWF52fZgyQKWFacPvrcy8I92xrkc6TJC+aiVbCvuo2KYFe9KRprDCV7eiNk8tFaSvSAvOIZNdStNB4LdO6qHPLtbQjeP3vWlrGqGJXgv+uzCb4Op6vLRbum5zYHUJcqQDnKqMwcWIujvIY43O4qu3IDAzExnvMKjMwcfFkHcJPonVgL7Qe/OuvRtc3p1Q1WNKW9BJNcdqKftz7lnVvkrMWUkDQFQ+MlGDpGVVEJDuX9By5z4MiPzzSuQrLl/iBDG/Cnwid4ofYJc6Ee2BSAZZ8IpG++nCICTNOju0MYu1nI93szo58QrN1vTCnJb/8Vu/pAfiEvzQ6kdGP+zo+lGX1MjWox9dwkUFlr/3Toe/G53xzSSl9XfwuYe01O+q9E25cpDblQHiU43VevCqCBYLb0t1lyhoA7duuNNmYwdmVnKj7nIJNq/pZGNkrGNIZy3CHPFOaUji9v4slisvaU0daKVbzpOWk+GWCIK1lW5puZlFrg0sFnGFo4+/TE/q+2xPwVsHpzqjoQiwDznnWue7JhiWNdwHsAQLM+jnOgNx8ZtJvhkyfeXDmkn7CAcVEOLc+HMfvyQyvuaI9b05IppyeK20WcWzTBdhObVAWxmFy4gTelQch2D8yz22p7t3JFnDw4bCry3avubJLxXO6xNDrtF8+P8VtM27dUASlpwjQ93a1o9bhgws22sJxgcoJl6VcjU487bStAmtED
  template:
    metadata:
      creationTimestamp: null
      name: immich-db-secrets
      namespace: immich
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgAnMVJ/noEybRDSTFryymRrXLBkBHQsbqZeuXqe6R9tXvpH1rnqlVsjBkfGO2oRBy+a6qvKZtQ4RyIvBA8l0Vj8ETy4YqlHztNc36Wtu+e1o9L1wc1iK8ZDtkE1cGCpTFjGMbhYD2mgBGET5JDneDXxLSvgNjsaU4AuZs52kBwu+8pkwm1NMHMnHM3PmK/W7XbLfXUkhfRourBKOa6MXnXMmJj2VifZypqvJ/srB7mLQWQXN9/WLQXMjRjw+s+TpJNuVoe3/oVV/OHHxJvNn1/m4swPfVSh/BqHcs1p1pACSmyEfJ6b1I+lCHcfrI8N0dPn93LYYk+u+vJOOanC+hlTuncQg5uSzboeP239yHYAKsW4WIFDfqnU5VnXX9ARvthcO1qYzLPELQz9cM3amoR+FcGOF2rHKpH8XDlhhZJPBs1FKfKQNt4tzwlGTyr18nFD8A0obQ+VLT0o3HGBmcNV1FM4MegWtgStL0MYbA4tndtkLzIMKLd9ezmV10Iqhmo7ZdvocnzYGb110wTU3qzSazcgXE2g6NgfrmFmpIFj3hoQtg09vzVu8o5WM7zAK8vykZsEVH1RVRdIo37+/Lmdu6syPS7XuvhDMBJILJMIQZkY4H8+W1Dt4kgyEKfguaeVFWLWKRn6pfdve1OV+xLAj/fYWFfyvKP98facoa7S7fq9kPfum7cIpCFParueAKLkt2D42Ueoi/CCW1aMGBzhQfr2cJ9+DOX8jnqrR0rhrB0LUfPE0zbHy51StelJ2oajVFR7uxwJ7uNl2+EL1TXTqNJtztTBeP2o8aueySjbXTq3NQOO3xoMHLHP9lhQVtEbBau1cZrOOsosOR0FBqOYr2MOvYxe3qCANNssvz5nmZFxjvZVP436yEE9FCXALyg6C0r8IDQ8q39l5foafOOLjGSLy8rmUb9ZRLT+8BcXs35zjGBXZu/r5jtyPfGc5xOApWYuWxP0vSpD2ExiX3GCy2Hr5f2LKN/4HJGICVxspoFqNQIZu2pKQSXaQKK4hKLf6yY4FYVHVwsnqBBj8qki2Rg4Oki9FLZacyh7mUinlPfO5AvmgXESJwooVsPMMMkSMvpXEKzye3YNGvO1xUgV91k+Fgxs3xsNGqPP+LJQL+GpQNtHX5uYOMdrTfDAQ7H5wKH7y70luHUZrZdTCU9DdebGuO9P3MuJ3DVjx3QUhJy+6UqHA075//o/ONNPcb5Ulw0oeWC6X3wl3Og1u5beYH95X6yqhoOutZPJ4fmcPxZo8KdFeBCIgCZWzi48e0VNyIXo9bOzjhZnZlvy
  template:
    metadata:
      creationTimestamp: null
      name: immich-config
      namespace: immich
