---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-db-secrets
  namespace: immich
spec:
  encryptedData:
    db-password: AgDCAj329OJcDEBYpnfJC/umyVJ+YNPCIBt7JAAPsO2WqgWF52fZgyQKWFacPvrcy8I92xrkc6TJC+aiVbCvuo2KYFe9KRprDCV7eiNk8tFaSvSAvOIZNdStNB4LdO6qHPLtbQjeP3vWlrGqGJXgv+uzCb4Op6vLRbum5zYHUJcqQDnKqMwcWIujvIY43O4qu3IDAzExnvMKjMwcfFkHcJPonVgL7Qe/OuvRtc3p1Q1WNKW9BJNcdqKftz7lnVvkrMWUkDQFQ+MlGDpGVVEJDuX9By5z4MiPzzSuQrLl/iBDG/Cnwid4ofYJc6Ee2BSAZZ8IpG++nCICTNOju0MYu1nI93szo58QrN1vTCnJb/8Vu/pAfiEvzQ6kdGP+zo+lGX1MjWox9dwkUFlr/3Toe/G53xzSSl9XfwuYe01O+q9E25cpDblQHiU43VevCqCBYLb0t1lyhoA7duuNNmYwdmVnKj7nIJNq/pZGNkrGNIZy3CHPFOaUji9v4slisvaU0daKVbzpOWk+GWCIK1lW5puZlFrg0sFnGFo4+/TE/q+2xPwVsHpzqjoQiwDznnWue7JhiWNdwHsAQLM+jnOgNx8ZtJvhkyfeXDmkn7CAcVEOLc+HMfvyQyvuaI9b05IppyeK20WcWzTBdhObVAWxmFy4gTelQch2D8yz22p7t3JFnDw4bCry3avubJLxXO6xNDrtF8+P8VtM27dUASlpwjQ93a1o9bhgws22sJxgcoJl6VcjU487bStAmtED
  template:
    metadata:
      creationTimestamp: null
      name: immich-db-secrets
      namespace: immich
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgAkvFl0U0ue5yOBsQy5rNJ5ZVmUIK17vpDSfNc8Vrc9fvedZJRFGPF6rXpSEEl3ptVLU0PA779ywOYO4V2EDRGg/yi5JjxXu+t2Bppc/hYkVDIfTKyNCNS4n6XtEGuz7eNF7w6nr/aWYi1jQmHwGM/JEsDZmWREgOClwAyLMj7a9vGFgtfzS9Gx5U32850wMRjZdTocPMcjMCwLkHoUej8ykkF5iHpdZSIoPUVr5aPNJVmGQp/ksHxD9YijZLwO/ODbVflh9p1rjsP3giCiFuls4GkBk122MGIaxjjCYaG36rpAKT6JUuIqF+avq9JELQ64ivr1zGPIpECwZncn2XPdv/BTJ4sBxLmXAUUt9IzesmCbd9H4KquCngMJgZLjqUEpG6/vsgyK1qTkK0bLKNIwHv73gICQ36vg/+0AIJsEkiDapNoyXJ5EQqeh/Qd61OFIqJOE5D65QHdUzPcmRRIn2GdN/Rl8rIo31RbScXShwxdEp9GS+p/kp2P3t+qKkaPwzT70kM31iNLK270fgLZ9Vw78jmJmT+ucN7XZFEG+9LIifoWY59OBOOZQnbUTnJxNgkpZvopnVmIVY4O2+cRWo1h4aSVtkVAPw/IxG7c03TP5bYlyHx5V+gPaPqO6RoO2aSDApvSDgptCc6xAkwCyOdXywwCXmBQloR+iyzuxJHXT7jlt1xrReDi5hGDQE9gLjkWOb8IwA/+6ih8OzVyjYElGA5A76ZtEZN44HurwGsQsjdLL7y4rUneYCnJ43PH4lRK4nn7Bq4xPas2QUoIDxRViC7vasVQK5zy6c3ny4W/o7vi/oN6QWB6ZZbpqT0rD790Q6VCAD/v4hQ14hV34xlJ1qpYK5rSsj0m0QQE4cHXo07a7ycAd/7FcK0pxu58czCEZVxQ5QT7Ys2r49lzbI4DmawpslptFDvpQq1n+hCgMeOG1wwNZKLQb75jz/0JvhF3XobEG0LvCa2SnBM7PPA92J4DvDyJ/d6jRrB7/0HRdiBwC64dgl86H0qzlTSE+CAOfRPWX+oenu2CSLLYljMguZF1ab31SkWz4u5rm/idyJMBn+PpAOwzlL0r0OFMu+zTF4CZTGiKhbE22w/NEap6x9a79V1wRc6wAzLNXgkFGG8sEjgElR39qJ8dU0RhnMHwWLWaE3B1bQL9ue/Qm78o+lflIfJax+2Xapx+EHdhFU/PVWU2TARR5I7OJIzDcu+oyZtDl4/FIusAQh4KdSIEv387C36sBCroJmQL80MdBue1FXodiWQ==
  template:
    metadata:
      creationTimestamp: null
      name: immich-config
      namespace: immich
