---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-calibre
  namespace: homepage
spec:
  encryptedData:
    password: AgBh8Oo92MxgVi/Us4t7w+mpf+uXEZxaOBCkseAtnmHpbmnew5iqFlGUcYL8SgArFtHS9rJeMrfY8aw8eJFYTaeaFSuMIMO7wDN2ppGPoeeYkMnKAZGn50GA50TVfzxCNABJVUm/QWiRZW1lXFTHqgxpGc07NgjHC2RVp4zY4Tf83X3UbG42mfy20BLsvGZEDNDkwN/tGBiX89qvAb21uzo6R9RHPMhfljy2dLXM0Hr42mYlQ7VfCZRT/Y/ONKkibNXOKaF1VKkCp4FMljLebe3O6FGdDJgiDQYjZvznrVL6i/DumOBV7ShpA2QsP1BpDx/sJwjPjek+Z2AucoqPXR0Gx6yWNRMuSOPLgUFwWVtZOkBSbMmMpA72tv5y7msNpxNaXF24kSc3Px5Sxp7o78fTke+gKpijHk/RFVYt8Y9dgaqSFwTjKCT3TtqXe0U3SWWVEqa/iWuDL6vjzKG0QKa695QOu0fghZWEpRLPTDh1vXiUZQpeKXPYYKd/KXptIaJSe0c3GS2da7qlmxQ1Ar0QqmfE8s1uKbrhl6JcJdLnhdJ7yyZa8mFYfelm9TsGeiuKmCzao/qRdslajoDbUjX9qZ3ThoNZ5miOym7q/lTsUew9jPX6KKoCLxbsI4hQg/EO8dhwk3W2en9mqhHWienCUJiIW3DyhIx70ZAOpxbvmrV4ZT7RY7nv3gMHIZlRJIWKrGLP9B7piSEPs35DFfAJ82XaDzI=
    username: AgAqdtVbCJHV0A30PtnmS4iJJPbWuYTsFWW87jp2iVrW0ttuCLQUItkgvYEhT/iiIzesuMWYeoC1r4W9148IozAGYrbaIWdxag5jN1iGFLqoRLLTMNXfDRoP/fOptoR61KAZMUieo5tzsPxXS1m6JbrEChgRc3muwQqiLQZ+O7jLrPCWMx/UdaUWfn5XokqQRxY2mAO836CHhEkIstoC7z9vIV36uIdKtqk1bVoe7Kf5Q6EPEhP+3WYanM0kjJfnreBRuKpk+FNLEXy1ReX/VPDaLxiaadjMI6to9KpW8irh4sWpL407260Wt9jPWwhG6ZGXLDn112uqaSJ9UwD3VPVpMU1IW8ycCkN9QV/gp+e8G2aXxQ+Uvzg2iskdqCFcZNDvG3ih4qlKbs2q1evxlB84/jD2TVg+d5xN4mOxzI3DGqgrCAr3BIChPcndGZyaNcmMZTpYaCmQcqsoIIJ+x/0UZcOJCTABHyi+jyberFBlVYQDa6QUkWykdQRPacMs5a3eb/wlYpVJvd7CWSZWvB2U1Asml63iEFXPxPKxOelTDwsKgJc2OLMWVnZ3krUVPyu4uShR9kJeBueK5izf2/zzUGvRr3m2EKm4bUPdnKQHVVDvEGoH5hmnGrE4Nu3Oh9bZDfPooel5DcGLu5LjkFQLhEWtzRg6JnknaQqpZRbBxn5cN4MHexB8T2T8UTRglUE9QpzQnQ==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-calibre
      namespace: homepage
