---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-nextcloud
  namespace: homepage
spec:
  encryptedData:
    password: AgCukzGatALQBUuaY0WUYDzS2mCjDjIugfvpbg42eSjXnK/TlhUBlRWe7TWY62Skgc0XXKe1WVowo7rhBumlivIxmVVuL1C5zAxCpIpcRiDmnVh1TGD+NaTH0emFv8U96TxbjC+OFir5mUca21jydmDtc6PMTsmrgDVtR4U2RHzboQKEJnv9XHGD7mWO78K4ImE0Vm0x/v+S/NN/EagPKBrFx54DGut45Ny+3G+Hzm3+G+FtiCV/h+4JQ/bNWnLM0j98XPp3u4Af5VNeyXyq8RHujeaEB8IH5udQ7sHLqyQxXKXPtwm6OvGFGcBcbo9l8LhPQqAWIQa14yFXmaVco53BjcpxhKN6GysGziCYws47pRzlZIIgUPI4xL+4lQK2fw1SU9AyFTYxO26GBe8CV+xN0ogpwUSfhrkz6Q3e7femBGSqVdNeiB/BLwZ1kNmEVi//ZFKgECKhe7QtNoPbz7coe0gUa9L1UTPcfL+P3YU5J7tP4o9Hfhlmt/NnzDfQoQ1aF3Przr3x0ENR4MywkpJ5N38R+iAiQjVdliAEjT+cceSWsbCc9N8L+mPSDCy9xLocyf9z8rdKZYfOOfbiyXO42gDJELSd47nWVpD7FwCaU74nvcTeqfrYGuVpzG8jWpRG2cX2M7zzZAqvFMHnyK9+Nf2RikFt2dqA3lT+4gi6eUDFcLhwXGx4UyrVcPJNNNgylK/rlUELr01B2xC8LVKjgj35oUACVpc+8FaN/lxmfg==
    username: AgBxjAI6CnVyoLxCZ4waDZf9Jx0rQPffyvcBpc6sTnCuiRb9+MgdKNvjHpIUPqL+jtxFO9cvY5Aw1Kyji4E3QpZhcfLPtd3SFdk2U3Yh6Aib16f0nhkvjYMcnEEsrAdKincD2U+dYKu7TSTOphQ9UkXb3k9jVCwd/bgnIxcCKSmstptplndhypGEPe/3DbMYJOFTVq6dI38yC6AlLOaysy3qy4xJMuOKiFykCT5EfQzALGJC3+AlahALOs6ham56Jm3lepHtiYbg3WHk79Rj9AWcEVjzWLfME4WSUHopy/BT8Y3DLMN3ld9udUf74Fx5Qg6TzKuVAEAjFDLRP9iSDsMpdr0hAPljDIYij6nuYqP4Q1EhfabkXSKIJGEQqn8jcFMbr2pHP2f0XmwkIYM2iiSegWHJ9xDfMmXI5ChbbwpL1DboFj86XqXuKxtm9pE5nmBmsEFmnnGIn9ggc/YOep9wLEyQVH8eMdmdLtmoOdrUZqeKkNMPaGLwBRfZOZTKX5Efn2mVainEuFgwOW9b99S3mXMBaoEyVlhFar6lvMW8dHG93gn20zLO7TRNnfNvi7+kH2ppnnXFon5l/nU/NUBt6V7VQZY1xCC8yOJlv67nF57TRkOntJdAHQ7W0mRAnwG3tHl/OeN9mZ3UnAzBf1Tg47T7iEu0aaxWtf1J9ZYxlG5vkeGwOy8YH3vNZdzhczax2mPWiQ==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-nextcloud
      namespace: homepage
