---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-calibre
  namespace: homepage
spec:
  encryptedData:
    password: AgCiFMlPpkblfqteah/kb8stRcGCRqcjL0u0NuB2iAiUKqYEups1B36WkI0rlsDSfSOXb6UfEhqkZ5CJ2/n391u3Z5a8DwQKqvMS2NEkOt4oZKk6vnrhs0dnWQ6bJazMtodIRWr6faIuS7Cp3u0TzaqMyG2eNI89tcNuvoQNbF+S5zU13A+T5NGefkAzXqHxerDky7SrtnxzdzbJV76V3wpAPDA5pBg/Uv67VIZTaiSeJ/f7FUFD9Vx9q5c0CEWqMWtRDmtAI8P7j7Q7bR0vmez2RiQOJlhC9nHTRw3PcFDefQt1NRVImR5wD5V1Sn+dicLoTAI9Ec1gDQOBO45yoENpN9N23RzTPutngVOByawfQJWd/f9hsOe6uHnajhYEQzxzjNjqe9GAZaTF6W/RDhrC5dp51Ju6yVVB+xfAX59x1Hmk5l4quIbET+pWzMEhOLu4slYTfk5KWPQT/UtB5wLWdIsgh+6ES/eU1HQ4miL8tdJw8pQxWQ3k79eZv5LSkLKt3yPpRXvRw+WMwdaJjoPITGXYZ1EwTUjoVzCpFrdutWN8do2XfqcQ4ngQ4Cc+4SgP9s6Gq3b3AYB5jhmzIpYPxBfjYJ5f35Zq+QwMekdxWKyswe2N6ubjvj+AUm/TDb7tzY7EIGLn5XUbpjfnhxltLUFosp1BqhYcWAF5ZWFdJmw4Ch9+oquftJjdG0oTC1aWhFIl+1zkTnW+1gI=
    username: AgCgB7F4WAOuBiBBzI14ahd0eIOwvJDa7l90cuPW01YEQcJua8zOIC/M2atl6tfomCGI5bhSlb/GVoXPB5GHGArlIWxwTulhoThN/495uISqTQbTBctuu1nFF1BPYFkPtGQOXmm6GVA1CfEwgDVFjUPjC4fdCgp1FzYq+w1Bb/PR95g9PrLTixpd2bMp0HCUnFn3rYv3e2b69v6os4Vmfrpqw/lFwoAX5xmXSpE1iDWNe9eKX90IVD5DMd+oZ/+PEZUBQ0loIDA7JRTQ1AhwF1a9MFfIQJ9/LFn+JFXM1LT/4c9BTwvY13R0nKgsrDyOHcSoeZ/RnJShLvcCxQfT+XxoagoFX7fmgI25bBEf0RK+S9YSNRQY7XDliXriPWwUpfod02UD+mzQOV/5b2IYfNKGlmPezUJo3hCZ2B9jrDgJQduJvKODq6ENrjzg7bI61+Ozmco6+boV9VzVbkzKOs0MebaJyFoAVPyQBS6+FiISTZyGyLSUDJIaqfY87g4m+Q9BzS1Dk8k+mHBS4IItDdfomSmjgOaSYZZUrDP5wOE0lhSl7hWOoqL56Znp53daToZYqUCBFRogXVn1Wh8bO9GLNUlUhvOdO8MahoWV+FXMhUvC70nNhGuYyNEiLsbT08Z1mU/qYPOxtKzmjEyNUPOxFb48cVm/p/mRXZGnT4umZXg1gmGvwte8Milxr/sPUp96fgAV8QQDpA==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-calibre
      namespace: homepage
