---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-proxmox
  namespace: homepage
spec:
  encryptedData:
    secret: AgBfIBfkjKcY3qcrD79HXbE4yZGd85cLNEK/ijyB0uZyIGhA4N4x+YLUkRA1TbPWzXFFL2V67DaZac9Iq29axMnemsBUYcPA5G2KJRSXf1Jom9cT2ZIt4OOSpGKMNyhRsCO6ME8gyCfc7pzpm472EQ9BGkfnl2/9bOg2lSnrmzwZB3oPcfvXfiEnZGasw+uMDILuURUcPANYVp52L0M7DxDjNn3Vh9PTZ4v1N/N0ObAeY1ulAOg74hbgCraECep0hmSuTddZVHeqDtSLb3bW864vZYHc0VV6tQgH4xPUqcPFAaZyyC/X5mLGhoZLQxRvPQ3x6JvlWVjBAQz0G+VEq2plC1nKrFsimTFRwA3JmFRm7+c/Hm0qeV3a6cmz/MMipw7fGzmYUqSjrXygTYDleaqiVzjkAWPyZFnqlrhmhSDqWsERf59EcYgF/BpzhnNq+7iog6/lutdVkiJYj95nOvLTuM1LiNXWZ0aO71eek86jYYctSKeFqQceB9rMnsBE3TO+wsQNlhI0nbKdtsshaE4JY4611haECowLDqzo3d3+S67sjQfhJcm7mqQBpedJ806CCstW+vKG6+D4SRweNZqKwbr/SjX8PMfGXnuG6spqG2KDeMYuTK4JOx3bUICoA2ElQEwAvs+tvCTaF/4bsYdHM6kYT8NNxMTVt1BwUg6M33cWmfFwBW1EQr6ncp98ke9d4QGgQ0TP8lBzfi+e8bgjyuPgJhlbU/8hg+wgETGajCH2am0=
    token: AgAFueBfeHab2B+brBjiZ6cdoRVAxvQYm4sW3HUOKht5q7B72U2+uFF1usQVm0ETL4JaE9lbLdjawzhjabQw5C7LroXGW3YUvrxAEnxrCk/vOrOVM8XSmuxCRMKeBuSx0kuni+O0+CZFhqpgNoP8tQTLWNEdTWsGWSu78eoqNc35zFTp79nR4OL2trxuv3BwsBtVd7ssKK5t9Vvx1L/Dl6HwN/qOQpqc2JzH7IrxRVPU4m9gGk7LRYQqRE+FZBjhYwhX+bvnvdU1VoOXV6RqkzduEUhez1pDQ2PzvoEoOZpqpfrwe3Yq3Q4Pd6mcAYU7ZBzDL+fWzBI+X9pSJ7OfCEQRKnXbXlM/TQ+ii8KqZyha4YKOoClcMZOAvCGW5oArquVDj06D3+IXA7a11AjvLDM3BTlWk9/CuzMPg6fbQLXFl6enByvb6Z9bK+kx9Jalkh1SwY6HwtHplJJ7uxfOfdLO0WDvpNf5LBkpMhjYSbENFRHZMn9RHV2WsFE0/8Uw9K5XfoysXuk0ZKRterpzFyAZFdZLgTYcdixwoaMoMt/946fPXWLNM+Ateo276MeDefJIzNgp/PCr8Sg7C5s3a2FQAIOtHIgi494mn81CLVI70Oj4k3NWgcDZhVCSK7BfzhJVvYte+6lId82EHVf5hc6RhqsVIjALaxQdyhM2tDYaa4W9wQWnLbWKI766R9gscb+qOv0yJXiS0Ogfk94sRPMsNQ==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-proxmox
      namespace: homepage
