---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-proxmox
  namespace: homepage
spec:
  encryptedData:
    secret: AgAiYXjbJk889hk7Kd4yAA4gHnkWKfXR0+qKp0GxUgcQzYl81BPygiqphkLuSRzKOYPdjPFQWw4j7aZP3Msjdh8QJPmVa+EcGDyezlmiVp0iyMSmcUXd+9r3MButFuMlCkFA6XR4rhFlaHmDNRV9+xJ29VwMQG7U8oTFLT+TOAUO7raAXdOOOw8mz2Kt0OGdNCUHh2BetfzpX8DNdNd8/zBb4Ugn/8ZXfPORitUjLk4QSSxLONlZaaQ2hcx4/ZopXCl/5oxhitJc1+TiB/rIYOAVDEOymnD+Ah9+Nm4x7kV+28ak5ddXQ2dQ4ie96mDh85Cl4K6k1dTzhCRZTErhqR1GU7kYEQRDkpv+4Nl5nPNaxLFvorXhXDpupvV0xdE8vE6kuGYyNW9+H+2KetUdu6sdHORSLlONWiZwPJWzT9OsjFC9URXdv7p6GizpgivhYnSxeiEswxI9i/dEmafdiK6Z4T/ipLTmi35UnfSRMvu4YGt5nk9acYOj3flN0xNHedJ3crfaFRVTrhg9lvsrmN9V0SKliQ74PGC8I65Zc4W6eWwmwdcbqkYcmz57W/iGN0VrHUVb2+0WLF8ry6QrCLZ6yC3XmVcYvME0fKUz3qSHe4xpwy+m+eHHxgUlD7N2lu0pPuwgfxASYM85RaCFa7VxKy4eH1Yb8thTZztKfFNyhKOTW+NOk3rh9U1lABYhALiNXQ+RXXpP3ULN5VhABA77e0bM5NO09M14kHDrxHb8PZE+TGI=
    token: AgAFueBfeHab2B+brBjiZ6cdoRVAxvQYm4sW3HUOKht5q7B72U2+uFF1usQVm0ETL4JaE9lbLdjawzhjabQw5C7LroXGW3YUvrxAEnxrCk/vOrOVM8XSmuxCRMKeBuSx0kuni+O0+CZFhqpgNoP8tQTLWNEdTWsGWSu78eoqNc35zFTp79nR4OL2trxuv3BwsBtVd7ssKK5t9Vvx1L/Dl6HwN/qOQpqc2JzH7IrxRVPU4m9gGk7LRYQqRE+FZBjhYwhX+bvnvdU1VoOXV6RqkzduEUhez1pDQ2PzvoEoOZpqpfrwe3Yq3Q4Pd6mcAYU7ZBzDL+fWzBI+X9pSJ7OfCEQRKnXbXlM/TQ+ii8KqZyha4YKOoClcMZOAvCGW5oArquVDj06D3+IXA7a11AjvLDM3BTlWk9/CuzMPg6fbQLXFl6enByvb6Z9bK+kx9Jalkh1SwY6HwtHplJJ7uxfOfdLO0WDvpNf5LBkpMhjYSbENFRHZMn9RHV2WsFE0/8Uw9K5XfoysXuk0ZKRterpzFyAZFdZLgTYcdixwoaMoMt/946fPXWLNM+Ateo276MeDefJIzNgp/PCr8Sg7C5s3a2FQAIOtHIgi494mn81CLVI70Oj4k3NWgcDZhVCSK7BfzhJVvYte+6lId82EHVf5hc6RhqsVIjALaxQdyhM2tDYaa4W9wQWnLbWKI766R9gscb+qOv0yJXiS0Ogfk94sRPMsNQ==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-proxmox
      namespace: homepage
