---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-nas
  namespace: homepage
spec:
  encryptedData:
    password: AgChxkf9m8VkNLWLYZpWQcIBdfIB1IIKb6aO2uVp37gkyehLiO3xU2vTPiFAttB2quy1fDtYXqt9LvJpQ1ldavWBNE6J5yVTlGv2HDe1OBV+D0vhT/Cd2fzaiV8T8R9ZJyoWbAuhY2a5ZNgpVPri0pHBNSKhWqBn+xGMv1Ig3+hCnwm5EhAOAFYp+lU5e6G+y8hr0xOO5r5cPm1LBz1Kv3JARYrgpsvSUKSiNkXoRgZRRUNL57i/njLn4y8nG0rIkZL5BtoPjHGYgjFsszmBu0qWX+gaiDjpVmyu4RauJYqGjwdG6JrObdgYbsPw2KnkWmtJQLU7UDLnIdPDQ/gCPylemWy0xqxrKsQqo+b13Tp4gP2htHUnwwn74vHpSVE/o7P0Ac3zONgMNs1kctfskR9zaRs/HINjdkc5r++8HiEZLBIRfDyrbJFJCoocW3CxuDzCIZy0ZLCM7vZVUr6CE2GLhVlbge4qwMQkFoJr1iqntFKT9VYAXC3fy70CnOHxp6+n/STLHffclfxjloKwZo8bGvoZySROvjw5cd+vIvuU5Swf+DLjBQQ7Lck6HyQI5T4Vkc8HUl0jCnd/agoykf0CwlafZBJqwF6kRotekq2G6lm/H23wIJvu59iaGLTQu2ER7QClazntdkKc3w4+qmXu+tM8hlwwytNG7nGGpg2OQDlueeJ4hTEZdNfRHFJYCazl9j85swU=
    username: AgC64w5/j8UsTWKXS6JGiBmZ9fCFRjglunjvg5km84D3xXRozvX0m14JSw45h5Nn5CBxMIZaiozf1uQGb6efcIuCg2v5M5CvBCwqZ5U630fU4lIJnhAibBveVgk49P4VswSumWxOcOYZ12Q67FumRs//OhZFgQ+4VfEbzcs1N7hitKlwtsBGGYtrb1vhEzltQ138Q5EWADBGGsCNgst5cOBcySLD53Umr2qrUOLZ7xoVIL2tOJ7+hwxZJ0EZ9L/9RypkB3dxBE6zFkrbUMyKJZpGkcgXvi3z3rPgYlOWaHdWTiD3qwWSzP4OU6rq5ViUSVFSXaqQfFHBg7vIE1xgsvrEy24H6salfHTKafy8zLUd+CY1SJkivXSHOpSGc07SKqWar1FWI5cSoqxh6r4Oz8EDR8QeMJqN+1DoTihXsBJsabwTRAxzKbdhxqsU3XnSi1LRjag7qo8H9V+kLDqzQU+2oZRr4SHGudboMTwi0swyBSuep2Jjh47TD37oDCn9+M+4kIw1tJ5r0yPlIiAaar0Y7uvdavD4tHq0MahAnpZ812OjkQ6vwYYcm0jlYkmvI3fNalO48VzUCqJkktFFFAMnyT3uadUNmBSbJhOW/BRgqS0riOF/d+lXIpyZoNrNe+8i5SdbPXtR6oeNKsip8myzGm5cQQtWtQGSbB2DZZ+bM901x1xvDLB5T3zdaZzkR2H6Lo5PMTvAoA==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-nas
      namespace: homepage
